### ISSUE TITLE
TABLE_NAME & QUEUE_NAME ?

### ISSUE THREAD

**Issue by PaulMuadDib** [t04glovern/dog-bark-detection#1]
Hi there,
I am trying to run your bark detector (Conda).
Sorry for what is probably a basic question but what are the environment variables in the title for ? to specify a mean to send messages when a barking is detected ? How to use them ?
Thanks for your code !
Jeff

**Comment by t04glovern** [comment]
Hey Jeff,

If you are just using the Conda / Notebook you won't need to use the TABLE_NAME and QUEUE_NAME variables. those are just for if you want to run the solution in the cloud (similar to how I do it in the blog series I wrote)

https://devopstar.com/2020/04/13/dog-bark-detector-machine-learning-model
