### ISSUE TITLE
Is there a simple, end-user version of this?

### ISSUE THREAD

**Issue by SomebodySysop** [t04glovern/dog-bark-detection#30]
I've been looking all over the Internet for an application that I can run that will parse an audio file and extract everything it thinks is a dog bark along (I want to monitor the same dog and have plenty of samples) with the audio timestamp.  Graphs would be great showing average frequency of barking per hour/day, but minimally, just a recording of all the captured dog barks would work.

I've looked at this project, and it does appear an awful lot like what I'm looking for, but I don't see anything here that shows me HOW to use this.  Is there a step by step guide to using this for someone who isn't an audio specialist?

**Comment by t04glovern** [comment]
Hey, since this was more of a pet project I didn't build it to be used as a turnkey solution, however I blogged about each step in these three posts. It might not be exactly what you're looking for but could point you in a direction

https://devopstar.com/2020/04/13/dog-bark-detector-machine-learning-model

**Comment by SomebodySysop** [comment]
Fair enough.  I don't suppose there is any user group or loose association of folks who have experience with this process?  Or, I guess that would be everyone who has posted here?

**Comment by MTecknology** [comment]
It's unfortunate that this repo (and blog post) are just a giant pile of haphazard notes and thoughts that others obviously can't piecemeal together. This looks like the start to a very good and helpful project, but instead we just find a dead end in this "won't fix" issue. :(

**Comment by mr-joshcrane** [comment]
If you're not happy maybe ask for your money back :(

**Comment by SrzStephen** [comment]
@SomebodySysop 
The simple end user version of this is probably going to be the jupyter notebook. https://github.com/t04glovern/dog-bark-detection/blob/master/notebook.ipynb. You could possibly break your audio file that you have into sliding windows and go that way.

**Comment by SrzStephen** [comment]
I've made some changes in #42  to make make the notebook a bit easier to run, since some packages drifted to make life slightly painful.

**Comment by t04glovern** [comment]
Thanks @SrzStephen ive merged your changes in :)
